"""Add budget model

Revision ID: 9abd0ef27043
Revises: b7befb983599
Create Date: 2026-07-24 20:55:26.651688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9abd0ef27043'
down_revision = 'b7befb983599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('budgets_user_id_key'), type_='unique')
        batch_op.drop_column('monthly_budget')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('budgets_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('amount')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
